version: '3.8'
services:
  gateway:
    build: .
    image: amazoncorretto:11-alpine-jdk
    container_name: gateaway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHARE_IT_SERVER_URL=http://server:9090

  server:
    build: .
    image: amazoncorretto:11-alpine-jdk
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=password

  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "6541:5432"
    environment:
      - DB_NAME=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
