version: '3.8'
services:
  gateway:
    build: gateway
    image: amazoncorretto:11
    container_name: shareit-gateaway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - shareit-server.url=http://server:9090

  server:
    build: server
    image: amazoncorretto:11
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit

    healthcheck:
            test: [ "CMD-SHELL", "pg_isready" ]
            interval: 5s
            timeout: 5s
            retries: 5

  db:
    image: postgres
    container_name: shareit
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit

