version: '3.8'
services:
  gateway:
    build: .
    image: amazoncorretto:11-alpine-jdk
    container_name: gateaway
    ports:
      - "8080:8080"
    depends_on: server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: .
    image: amazoncorretto:11-alpine-jdk
    container_name: server
    ports:
      - "9090:9090"
    depends_on: db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  db:
    image: postgres
    container_name: db
    ports:
      - "6541:5432"
    environment:
      - DB_NAME=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432